### ISSUE TITLE
Make the Run Instructions Correct

### ISSUE THREAD

**Issue by rouke-broersma** [Faultify/Faultify#16]
The run instructions in the readme read as follows:

```
faultify -p YourTestProject.csproj -t html
```
But -p is the parallel option. This should be -t for --testProjectName. Also -t html should be -f html.

**Comment by TimonPost** [comment]
Thanks for bringing it up, this has the old parameters as it used to be.

**Comment by 96RadhikaJadhav** [comment]
@Mobrockers  Can I work on the issue?

**Comment by rouke-broersma** [comment]
I don't see why not, but I'm not affiliated with faultify so you should ask @TimonPost

**Comment by 96RadhikaJadhav** [comment]
@TimonPost Can I work on the issue?

**Comment by TimonPost** [comment]
@96RadhikaJadhav sure! If you need any information feel free to leave a message.
