### ISSUE TITLE
Make Parallel Commandline Option Optional

### ISSUE THREAD

**Issue by rouke-broersma** [Faultify/Faultify#19]
When running faultify without setting the parallel option I get an error:

```
PS C:\git\endeavour-cloud\CloudApp\InfoSupport.PDC.Cloud.Authentication.Test> faultify -t .\InfoSupport.PDC.Cloud.Authentication.Test.csproj -f html
Faultify.Cli 0.1.0
Copyright (C) 2021 Timon, Janfokke

ERROR(S):
  Error setting value to option 'p, parallel': Check if Option or Value attribute values are set properly for the given
  type.
```

I expect the default of 1 to be used.

**Comment by TimonPost** [comment]
Thanks for the issue, you are correct, I walked into the same problem myself. Will be resolved!

**Comment by LukasBil** [comment]
Hi @TimonPost. Can I take this one? At first glance it looks like the problem is caused By Parallel setting being type of `int` and default value being set of type `string`.

**Comment by TimonPost** [comment]
@LukasBil yea, that is probably the issue, feel free to take this one.

**Comment by TimonPost** [comment]
I fixed the issue already, working trough all open issues ... Thanks for paying interest at least 👍
